# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

autoSwitchAppearance = true
colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark

enableCodeCopy = true
enableSearch = true

mainSections = ["posts", "categories", "tutorials"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false

defaultBackgroundImage = "img/background.jpeg" # used as default for background images
# defaultFeaturedImage = "img/background.jpeg"   # used as default for featured images in all articles

highlightCurrentMenuArea = true
smartTOC = true
# smartTOCHideUnfocusedChildren = true

[header]
layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
showAppearanceSwitcher = true
showCopyright = true
showMenu = true
showScrollToTop = true
showThemeAttribution = true

[homepage]
cardView = true
cardViewScreenWidth = false
# homepageImage = "" # used in: hero, and card
layout = "background"       # valid options: page, profile, hero, card, background, custom
layoutBackgroundBlur = true # only used when layout equals background
showMoreLink = true
showMoreLinkDest = "/posts"
showRecent = true
showRecentItems = 6

[article]
editAppendPath = true
editURL = "https://github.com/Armoghan-Blogs/Blogs/"
heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
invertPagination = false
layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
newsletter = false
relatedContentLimit = 3
seriesOpened = false
sharingLinks = [
  "linkedin",
  "twitter",
  "reddit",
  "pinterest",
  "facebook",
  "email",
  "whatsapp",
  "telegram",
]
showAuthor = true
showAuthorBottom = true
showAuthorsBadges = false
showBreadcrumbs = true
showDate = true
showDateOnlyInArticle = false
showDateUpdated = false
showDraftLabel = true
showEdit = true
showHeadingAnchors = false
showHero = true
showLikes = true
showPagination = true
showReadingTime = true
showRelatedContent = true
showTableOfContents = false
showTaxonomies = false
showViews = true
showWordCount = true
showZenMode = false

[list]
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false
groupByYear = true
heroStyle = "background"           # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true        # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
orderByWeight = false
showBreadcrumbs = true
showCards = true
showHero = true
showLikes = true
showSummary = true
showTableOfContents = true
showViews = true

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
cardView = true
heroStyle = "background"   # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = true
showHero = true
showLikes = true
showTableOfContents = true
showTermCount = true
showViews = true

[term]
cardView = true
cardViewScreenWidth = false
groupByYear = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showHero = true
showLikes = true
showTableOfContents = true
showViews = true

[firebase]
apiKey = "AIzaSyDuJI7aN8UqyibbCUn4LDIwnbJzgdtjy-g"
authDomain = "armoghan-blogs-aa5b6.firebaseapp.com"
projectId = "armoghan-blogs-aa5b6"
storageBucket = "armoghan-blogs-aa5b6.appspot.com"
messagingSenderId = "638030517122"
appId = "1:638030517122:web:352a7d26fdca848d4e359b"
measurementId = "G-T7WW2L6RBX"

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[umamiAnalytics]
# websiteid = "ABC12345"
# domain = "llama.yoursite.com"
# dataDomains = "yoursite.com,yoursite2.com"
# enableTrackEvent = true

[selineAnalytics]
# token = "XXXXXX"
# enableTrackEvent = true

[buymeacoffee]
# identifier = ""
# globalWidget = true
# globalWidgetMessage = "Hello"
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "Right"

[verification]
google = "x4mfCN8tLPQvaLugBp5JuK6IDtnyt6U7iVgB7nEZv3M"
bing = "F5E6FE13E3FE3C1DE25A0E210CE9A9C7"
# pinterest = ""
# yandex = ""

# Decap CMS Config
[DecapCMS]
development = false
branch = "main"
media = "/static/media"
public = "/media"
PublishMode = "editorial_workflow"
# logo = ""
preview = true
search = false
Cheatsheets = true
Tutorials = true
