# Dependabot configuration file for keeping dependencies up-to-date 🛠️
version: 2

updates:
  # NPM packages updates 🌐
  - package-ecosystem: "npm" # 🛠️ Node.js package ecosystem
    directory: "/" # 📁 Location of package manifests (package.json)
    schedule:
      interval: "weekly" # ⏰ Frequency of updates
    allow:
      - dependency-type: "all" # 👥 Update all types of dependencies (direct and development)

  # Go modules updates, including Hugo 📚
  - package-ecosystem: "gomod" # 🏠 Hugo and Go modules
    directory: "/" # 📁 Location of Go module manifests (for Hugo)
    schedule:
      interval: "weekly" # ⏰ Frequency of updates
    allow:
      - dependency-type: "all" # 👥 Update all types of dependencies (direct and indirect)

  # DevContainers updates 🧩
  - package-ecosystem: "devcontainers" # 🧩 DevContainer configuration
    directory: "/" # 📁 Location of devcontainer.json
    schedule:
      interval: "weekly" # ⏰ Frequency of updates
    allow:
      - dependency-type: "all" # 👥 Update all types of dependencies (direct and development)
