# Dependabot configuration file for keeping dependencies up-to-date 🛠️
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all" 
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "devcontainers" 
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"